spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/rking
    username: sa
    password:
  jpa:
    hibernate:
          ddl-auto: create
    properties:
      hibernate:
        show_sql: true